- name: Install Hireship PROD Apps
  gather_facts: true
  hosts: localhost
  tasks:

    - include_role:
        name: andusystems-hireship-prod
      tags:
        - hireship-prod-apps
        - apps
        - install
