- name: Install Monitoring Apps
  gather_facts: true
  hosts: localhost
  tasks:

    - include_role:
        name: andusystems-monitoring
      tags: 
        - monitoring-apps
        - apps
        - install