linux:
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
  hosts:
    managementctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    managementwrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    managementwrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"
    managementwrkr2:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[2] }}"
    managementwrkr3:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[3] }}"
    #managementwrkr4:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[4] }}"

vms:
  hosts:
    managementctrl:
    managementwrkr0:
    managementwrkr1:
    managementwrkr2:
    managementwrkr3:
    #managementwrkr4:

controllers:
  hosts:
    managementctrl:
  
workers:
  hosts:
    managementwrkr0:
    managementwrkr1:
    managementwrkr2:
    managementwrkr3:
    #managementwrkr4: