---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-pat
  namespace: arc-runners
type: Opaque
stringData:
  github_token: "{{ github_runner_pat }}"
