apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.3.2
      helm:
        valueFiles:
          - $values/apps/prometheus/values.yml
    - repoURL: http://forgejo-http.forgejo.svc.cluster.local:3000/andusystems/andusystems-management.git
      targetRevision: HEAD
      path: apps/prometheus
      directory:
        include: '{manifest.yml}'
    - repoURL: http://forgejo-http.forgejo.svc.cluster.local:3000/andusystems/andusystems-management.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true